import { Meta, StoryObj } from '@storybook/react'
import OutfitSearch from '.'

const meta: Meta<typeof OutfitSearch> = {
  title: 'Molecules/OutfitSearch',
  component: OutfitSearch,
  tags: ['autodocs'],
  parameters: {
    layout: 'fullscreen',
  },
}

export default meta
type Story = StoryObj<typeof OutfitSearch>

export const Default: Story = {
  args: {
    addFields: (data) => console.log(data),
    groupedFields: {
      Eichi: {
        general: [
          {
            group: 'general',
            Ac: 0,
            Pa: 0,
            Un: 0,
            Sm: 0,
            Te: 0,
            Ch: 0,
            idol: 'Eichi',
            name: 'fine Training Uniform',
            fullName: 'fine Training Uniform (Eichi)',
            crafted: true,
            id: '033cc2da-3f1a-4a41-84ac-b731075bec80',
            index: 0,
          },
          {
            group: 'general',
            Ac: 20,
            Pa: 25,
            Un: 0,
            Sm: 0,
            Te: 35,
            Ch: 0,
            idol: 'Eichi',
            name: 'ES Idol Uniform',
            fullName: 'ES Idol Uniform (Eichi)',
            crafted: false,
            id: '6a0e49a4-6290-4bf8-b4dd-90bffa74538f',
            index: 49,
          },
        ],
      },
      Wataru: {
        general: [
          {
            group: 'general',
            Ac: 0,
            Pa: 0,
            Un: 0,
            Sm: 0,
            Te: 0,
            Ch: 0,
            idol: 'Wataru',
            name: 'fine Training Uniform',
            fullName: 'fine Training Uniform (Wataru)',
            crafted: true,
            id: 'b23db829-fb2e-4fab-aede-0c6ecb3e185f',
            index: 1,
          },
          {
            group: 'general',
            Ac: 0,
            Pa: 35,
            Un: 20,
            Sm: 25,
            Te: 0,
            Ch: 0,
            idol: 'Wataru',
            name: 'ES Idol Uniform',
            fullName: 'ES Idol Uniform (Wataru)',
            crafted: false,
            id: '4b124822-c09e-4d40-8ee2-8b5523f28c1e',
            index: 50,
          },
        ],
      },
      Tori: {
        general: [
          {
            group: 'general',
            Ac: 0,
            Pa: 0,
            Un: 0,
            Sm: 0,
            Te: 0,
            Ch: 0,
            idol: 'Tori',
            name: 'fine Training Uniform',
            fullName: 'fine Training Uniform (Tori)',
            crafted: true,
            id: 'd06839e5-6d49-498f-a92d-ba8c38451cf3',
            index: 2,
          },
          {
            group: 'general',
            Ac: 35,
            Pa: 0,
            Un: 20,
            Sm: 0,
            Te: 0,
            Ch: 25,
            idol: 'Tori',
            name: 'ES Idol Uniform',
            fullName: 'ES Idol Uniform (Tori)',
            crafted: false,
            id: '6f41c3a9-a9d6-4e36-9656-f6ef19046b6a',
            index: 51,
          },
        ],
      },
      Yuzuru: {
        general: [
          {
            group: 'general',
            Ac: 0,
            Pa: 0,
            Un: 0,
            Sm: 0,
            Te: 0,
            Ch: 0,
            idol: 'Yuzuru',
            name: 'fine Training Uniform',
            fullName: 'fine Training Uniform (Yuzuru)',
            crafted: true,
            id: '0cb65a73-230a-47d3-8bb7-d516bff0ad39',
            index: 3,
          },
          {
            group: 'general',
            Ac: 20,
            Pa: 0,
            Un: 0,
            Sm: 20,
            Te: 40,
            Ch: 0,
            idol: 'Yuzuru',
            name: 'ES Idol Uniform',
            fullName: 'ES Idol Uniform (Yuzuru)',
            crafted: false,
            id: '10d60bf0-d631-42f9-aebb-674adda964ed',
            index: 52,
          },
        ],
      },
      Hokuto: {
        general: [
          {
            group: 'general',
            Ac: 0,
            Pa: 0,
            Un: 0,
            Sm: 0,
            Te: 0,
            Ch: 0,
            idol: 'Hokuto',
            name: 'Trickstar Training Uniform',
            fullName: 'Trickstar Training Uniform (Hokuto)',
            crafted: true,
            id: '671d9c94-9c64-4416-83d2-5c20b158710d',
            index: 4,
          },
          {
            group: 'general',
            Ac: 0,
            Pa: 25,
            Un: 0,
            Sm: 0,
            Te: 35,
            Ch: 20,
            idol: 'Hokuto',
            name: 'ES Idol Uniform',
            fullName: 'ES Idol Uniform (Hokuto)',
            crafted: false,
            id: '0765b31f-6981-4fb0-a4ce-1c37c1907309',
            index: 53,
          },
        ],
      },
      Subaru: {
        general: [
          {
            group: 'general',
            Ac: 0,
            Pa: 0,
            Un: 0,
            Sm: 0,
            Te: 0,
            Ch: 0,
            idol: 'Subaru',
            name: 'Trickstar Training Uniform',
            fullName: 'Trickstar Training Uniform (Subaru)',
            crafted: true,
            id: '1b2e9bdd-ccac-4286-9154-1e6ba36f0a6c',
            index: 5,
          },
          {
            group: 'general',
            Ac: 20,
            Pa: 0,
            Un: 25,
            Sm: 35,
            Te: 0,
            Ch: 0,
            idol: 'Subaru',
            name: 'ES Idol Uniform',
            fullName: 'ES Idol Uniform (Subaru)',
            crafted: false,
            id: '515a80e7-35ca-4c40-84ce-fc3dd8ebe86b',
            index: 54,
          },
        ],
      },
      Makoto: {
        general: [
          {
            group: 'general',
            Ac: 0,
            Pa: 0,
            Un: 0,
            Sm: 0,
            Te: 0,
            Ch: 0,
            idol: 'Makoto',
            name: 'Trickstar Training Uniform',
            fullName: 'Trickstar Training Uniform (Makoto)',
            crafted: true,
            id: 'eee9fe43-c608-45a6-b69a-1752a0ae641c',
            index: 6,
          },
          {
            group: 'general',
            Ac: 0,
            Pa: 20,
            Un: 35,
            Sm: 25,
            Te: 0,
            Ch: 0,
            idol: 'Makoto',
            name: 'ES Idol Uniform',
            fullName: 'ES Idol Uniform (Makoto)',
            crafted: false,
            id: 'defae8fe-3f10-4f86-99c5-2ad0a1c57d28',
            index: 55,
          },
        ],
      },
      Mao: {
        general: [
          {
            group: 'general',
            Ac: 0,
            Pa: 0,
            Un: 0,
            Sm: 0,
            Te: 0,
            Ch: 0,
            idol: 'Mao',
            name: 'Trickstar Training Uniform',
            fullName: 'Trickstar Training Uniform (Mao)',
            crafted: true,
            id: '959f3514-4050-4f09-9bfe-20b19bf8056e',
            index: 7,
          },
          {
            group: 'general',
            Ac: 0,
            Pa: 0,
            Un: 20,
            Sm: 40,
            Te: 20,
            Ch: 0,
            idol: 'Mao',
            name: 'ES Idol Uniform',
            fullName: 'ES Idol Uniform (Mao)',
            crafted: false,
            id: 'cd32028a-1366-4c31-a841-dc49660899bc',
            index: 56,
          },
        ],
      },
      Chiaki: {
        general: [
          {
            group: 'general',
            Ac: 0,
            Pa: 0,
            Un: 0,
            Sm: 0,
            Te: 0,
            Ch: 0,
            idol: 'Chiaki',
            name: 'RYUSEITAI Training Uniform',
            fullName: 'RYUSEITAI Training Uniform (Chiaki)',
            crafted: true,
            id: '77d5ee50-b4f5-49b3-b4dc-d6b297f8c4fe',
            index: 8,
          },
          {
            group: 'general',
            Ac: 0,
            Pa: 0,
            Un: 20,
            Sm: 25,
            Te: 0,
            Ch: 35,
            idol: 'Chiaki',
            name: 'ES Idol Uniform',
            fullName: 'ES Idol Uniform (Chiaki)',
            crafted: false,
            id: '322341b5-1e12-4c67-9da1-7ff580bf4276',
            index: 57,
          },
        ],
      },
      Kanata: {
        general: [
          {
            group: 'general',
            Ac: 0,
            Pa: 0,
            Un: 0,
            Sm: 0,
            Te: 0,
            Ch: 0,
            idol: 'Kanata',
            name: 'RYUSEITAI Training Uniform',
            fullName: 'RYUSEITAI Training Uniform (Kanata)',
            crafted: true,
            id: '5dc4a1b0-53b1-4a83-aae4-17f1292b1562',
            index: 9,
          },
          {
            group: 'general',
            Ac: 20,
            Pa: 20,
            Un: 0,
            Sm: 0,
            Te: 0,
            Ch: 40,
            idol: 'Kanata',
            name: 'ES Idol Uniform',
            fullName: 'ES Idol Uniform (Kanata)',
            crafted: false,
            id: 'a7da8b47-bf6f-4083-a902-a299a4d998a6',
            index: 58,
          },
        ],
      },
      Tetora: {
        general: [
          {
            group: 'general',
            Ac: 0,
            Pa: 0,
            Un: 0,
            Sm: 0,
            Te: 0,
            Ch: 0,
            idol: 'Tetora',
            name: 'RYUSEITAI Training Uniform',
            fullName: 'RYUSEITAI Training Uniform (Tetora)',
            crafted: true,
            id: 'f34b0546-5949-4ac5-b5ff-b8b3f1141d82',
            index: 10,
          },
          {
            group: 'general',
            Ac: 25,
            Pa: 35,
            Un: 20,
            Sm: 0,
            Te: 0,
            Ch: 0,
            idol: 'Tetora',
            name: 'ES Idol Uniform',
            fullName: 'ES Idol Uniform (Tetora)',
            crafted: false,
            id: 'f94ab655-3fad-417a-80af-92dc25d13a5c',
            index: 59,
          },
        ],
      },
      Midori: {
        general: [
          {
            group: 'general',
            Ac: 0,
            Pa: 0,
            Un: 0,
            Sm: 0,
            Te: 0,
            Ch: 0,
            idol: 'Midori',
            name: 'RYUSEITAI Training Uniform',
            fullName: 'RYUSEITAI Training Uniform (Midori)',
            crafted: true,
            id: '81288575-6118-4142-9ec9-301cafe8eef9',
            index: 11,
          },
          {
            group: 'general',
            Ac: 25,
            Pa: 20,
            Un: 35,
            Sm: 0,
            Te: 0,
            Ch: 0,
            idol: 'Midori',
            name: 'ES Idol Uniform',
            fullName: 'ES Idol Uniform (Midori)',
            crafted: false,
            id: '6ff00f0b-12b1-43fa-94b0-056a99eacc3c',
            index: 60,
          },
        ],
      },
      Shinobu: {
        general: [
          {
            group: 'general',
            Ac: 0,
            Pa: 0,
            Un: 0,
            Sm: 0,
            Te: 0,
            Ch: 0,
            idol: 'Shinobu',
            name: 'RYUSEITAI Training Uniform',
            fullName: 'RYUSEITAI Training Uniform (Shinobu)',
            crafted: true,
            id: 'd715bd35-f0ac-49c3-aa3e-a2d4a9dfeb4f',
            index: 12,
          },
          {
            group: 'general',
            Ac: 0,
            Pa: 0,
            Un: 35,
            Sm: 25,
            Te: 0,
            Ch: 20,
            idol: 'Shinobu',
            name: 'ES Idol Uniform',
            fullName: 'ES Idol Uniform (Shinobu)',
            crafted: false,
            id: 'df8b1ad7-9ed5-489c-abeb-b5f51c3629c5',
            index: 61,
          },
        ],
      },
      Hiiro: {
        general: [
          {
            group: 'general',
            Ac: 0,
            Pa: 0,
            Un: 0,
            Sm: 0,
            Te: 0,
            Ch: 0,
            idol: 'Hiiro',
            name: 'ALKALOID Training Uniform',
            fullName: 'ALKALOID Training Uniform (Hiiro)',
            crafted: true,
            id: '8523e04f-4fe8-4e6d-bcbc-209f9e035890',
            index: 13,
          },
          {
            group: 'general',
            Ac: 0,
            Pa: 25,
            Un: 0,
            Sm: 0,
            Te: 20,
            Ch: 35,
            idol: 'Hiiro',
            name: 'ES Idol Uniform',
            fullName: 'ES Idol Uniform (Hiiro)',
            crafted: false,
            id: '226372dd-03d2-4355-a5e6-b4c473117f6a',
            index: 62,
          },
        ],
      },
      Aira: {
        general: [
          {
            group: 'general',
            Ac: 0,
            Pa: 0,
            Un: 0,
            Sm: 0,
            Te: 0,
            Ch: 0,
            idol: 'Aira',
            name: 'ALKALOID Training Uniform',
            fullName: 'ALKALOID Training Uniform (Aira)',
            crafted: true,
            id: '27412ccf-aa16-4d34-ba4a-9af73e7f4409',
            index: 14,
          },
          {
            group: 'general',
            Ac: 0,
            Pa: 20,
            Un: 35,
            Sm: 0,
            Te: 0,
            Ch: 25,
            idol: 'Aira',
            name: 'ES Idol Uniform',
            fullName: 'ES Idol Uniform (Aira)',
            crafted: false,
            id: '3d73185e-cfb3-4409-bb3e-ac8fa1df6101',
            index: 63,
          },
        ],
      },
      Mayoi: {
        general: [
          {
            group: 'general',
            Ac: 0,
            Pa: 0,
            Un: 0,
            Sm: 0,
            Te: 0,
            Ch: 0,
            idol: 'Mayoi',
            name: 'ALKALOID Training Uniform',
            fullName: 'ALKALOID Training Uniform (Mayoi)',
            crafted: true,
            id: '8822461e-8e15-4e01-b7a1-e99039af3968',
            index: 15,
          },
          {
            group: 'general',
            Ac: 40,
            Pa: 0,
            Un: 20,
            Sm: 0,
            Te: 20,
            Ch: 0,
            idol: 'Mayoi',
            name: 'ES Idol Uniform',
            fullName: 'ES Idol Uniform (Mayoi)',
            crafted: false,
            id: '99170a51-181c-4d3d-8f6b-1f015e0e44d2',
            index: 64,
          },
        ],
      },
      Tatsumi: {
        general: [
          {
            group: 'general',
            Ac: 0,
            Pa: 0,
            Un: 0,
            Sm: 0,
            Te: 0,
            Ch: 0,
            idol: 'Tatsumi',
            name: 'ALKALOID Training Uniform',
            fullName: 'ALKALOID Training Uniform (Tatsumi)',
            crafted: true,
            id: 'c36c97f8-bc84-4142-a12a-8cccbddbf1b0',
            index: 16,
          },
          {
            group: 'general',
            Ac: 0,
            Pa: 20,
            Un: 0,
            Sm: 40,
            Te: 20,
            Ch: 0,
            idol: 'Tatsumi',
            name: 'ES Idol Uniform',
            fullName: 'ES Idol Uniform (Tatsumi)',
            crafted: false,
            id: 'ec8eff75-18d7-48aa-a5c3-ce32a0f0cdff',
            index: 65,
          },
        ],
      },
      Nagisa: {
        general: [
          {
            group: 'general',
            Ac: 0,
            Pa: 0,
            Un: 0,
            Sm: 0,
            Te: 0,
            Ch: 0,
            idol: 'Nagisa',
            name: 'Eden Training Uniform',
            fullName: 'Eden Training Uniform (Nagisa)',
            crafted: true,
            id: '28bad265-3cc1-4bd4-88c9-846c626fec6b',
            index: 17,
          },
          {
            group: 'general',
            Ac: 0,
            Pa: 0,
            Un: 0,
            Sm: 40,
            Te: 20,
            Ch: 20,
            idol: 'Nagisa',
            name: 'ES Idol Uniform',
            fullName: 'ES Idol Uniform (Nagisa)',
            crafted: false,
            id: '6a0bf109-1cd0-4270-b1d6-ecb5904bcc03',
            index: 66,
          },
        ],
      },
      Hiyori: {
        general: [
          {
            group: 'general',
            Ac: 0,
            Pa: 0,
            Un: 0,
            Sm: 0,
            Te: 0,
            Ch: 0,
            idol: 'Hiyori',
            name: 'Eden Training Uniform',
            fullName: 'Eden Training Uniform (Hiyori)',
            crafted: true,
            id: '497221da-c8a2-422a-b78c-172111637351',
            index: 18,
          },
          {
            group: 'general',
            Ac: 0,
            Pa: 35,
            Un: 0,
            Sm: 25,
            Te: 20,
            Ch: 0,
            idol: 'Hiyori',
            name: 'ES Idol Uniform',
            fullName: 'ES Idol Uniform (Hiyori)',
            crafted: false,
            id: '2dfa3c64-130e-4130-a1c3-07f0533149ad',
            index: 67,
          },
        ],
      },
      Ibara: {
        general: [
          {
            group: 'general',
            Ac: 0,
            Pa: 0,
            Un: 0,
            Sm: 0,
            Te: 0,
            Ch: 0,
            idol: 'Ibara',
            name: 'Eden Training Uniform',
            fullName: 'Eden Training Uniform (Ibara)',
            crafted: true,
            id: '416a8e93-1a93-4b66-bede-03aecbae38d3',
            index: 19,
          },
          {
            group: 'general',
            Ac: 0,
            Pa: 35,
            Un: 20,
            Sm: 0,
            Te: 0,
            Ch: 25,
            idol: 'Ibara',
            name: 'ES Idol Uniform',
            fullName: 'ES Idol Uniform (Ibara)',
            crafted: false,
            id: 'c6efdf09-50a7-41c5-ace8-221eb6e1641c',
            index: 68,
          },
        ],
      },
      Jun: {
        general: [
          {
            group: 'general',
            Ac: 0,
            Pa: 0,
            Un: 0,
            Sm: 0,
            Te: 0,
            Ch: 0,
            idol: 'Jun',
            name: 'Eden Training Uniform',
            fullName: 'Eden Training Uniform (Jun)',
            crafted: true,
            id: '462d80cc-1514-4fc9-98ae-fcc66231c1a8',
            index: 20,
          },
          {
            group: 'general',
            Ac: 0,
            Pa: 0,
            Un: 0,
            Sm: 35,
            Te: 20,
            Ch: 25,
            idol: 'Jun',
            name: 'ES Idol Uniform',
            fullName: 'ES Idol Uniform (Jun)',
            crafted: false,
            id: 'b01cf26f-6f65-42a8-a0cc-ad3ac5389854',
            index: 69,
          },
        ],
      },
      Shu: {
        general: [
          {
            group: 'general',
            Ac: 0,
            Pa: 0,
            Un: 0,
            Sm: 0,
            Te: 0,
            Ch: 0,
            idol: 'Shu',
            name: 'Valkyrie Training Uniform',
            fullName: 'Valkyrie Training Uniform (Shu)',
            crafted: true,
            id: 'ddbf23a4-39e8-4e0d-82ba-89ccf5a6038d',
            index: 21,
          },
          {
            group: 'general',
            Ac: 0,
            Pa: 0,
            Un: 0,
            Sm: 20,
            Te: 20,
            Ch: 40,
            idol: 'Shu',
            name: 'ES Idol Uniform',
            fullName: 'ES Idol Uniform (Shu)',
            crafted: false,
            id: 'f34954ac-8e19-4663-aad7-7b2573ff767b',
            index: 70,
          },
        ],
      },
      Mika: {
        general: [
          {
            group: 'general',
            Ac: 0,
            Pa: 0,
            Un: 0,
            Sm: 0,
            Te: 0,
            Ch: 0,
            idol: 'Mika',
            name: 'Valkyrie Training Uniform',
            fullName: 'Valkyrie Training Uniform (Mika)',
            crafted: true,
            id: '58a8508b-55ff-42fd-bb61-b5977afb14b3',
            index: 22,
          },
          {
            group: 'general',
            Ac: 40,
            Pa: 20,
            Un: 0,
            Sm: 0,
            Te: 0,
            Ch: 20,
            idol: 'Mika',
            name: 'ES Idol Uniform',
            fullName: 'ES Idol Uniform (Mika)',
            crafted: false,
            id: 'f181e529-2ca8-4e98-8a99-8c68e0219d84',
            index: 71,
          },
        ],
      },
      Hinata: {
        general: [
          {
            group: 'general',
            Ac: 0,
            Pa: 0,
            Un: 0,
            Sm: 0,
            Te: 0,
            Ch: 0,
            idol: 'Hinata',
            name: '2wink Training Uniform',
            fullName: '2wink Training Uniform (Hinata)',
            crafted: true,
            id: '51896e20-01d1-4356-89f9-c89e37d8d73f',
            index: 23,
          },
          {
            group: 'general',
            Ac: 20,
            Pa: 40,
            Un: 0,
            Sm: 0,
            Te: 20,
            Ch: 0,
            idol: 'Hinata',
            name: 'ES Idol Uniform',
            fullName: 'ES Idol Uniform (Hinata)',
            crafted: false,
            id: '98806bf7-92b3-4a1e-8451-1b184eab3267',
            index: 72,
          },
        ],
      },
      Yuta: {
        general: [
          {
            group: 'general',
            Ac: 0,
            Pa: 0,
            Un: 0,
            Sm: 0,
            Te: 0,
            Ch: 0,
            idol: 'Yuta',
            name: '2wink Training Uniform',
            fullName: '2wink Training Uniform (Yuta)',
            crafted: true,
            id: '15e4ab4d-e319-4661-b42d-020b05c74bab',
            index: 24,
          },
          {
            group: 'general',
            Ac: 20,
            Pa: 0,
            Un: 20,
            Sm: 0,
            Te: 40,
            Ch: 0,
            idol: 'Yuta',
            name: 'ES Idol Uniform',
            fullName: 'ES Idol Uniform (Yuta)',
            crafted: false,
            id: '4a770a59-e552-4223-819c-4fe9e5b0aae2',
            index: 73,
          },
        ],
      },
      Rinne: {
        general: [
          {
            group: 'general',
            Ac: 0,
            Pa: 0,
            Un: 0,
            Sm: 0,
            Te: 0,
            Ch: 0,
            idol: 'Rinne',
            name: 'Crazy:B Training Uniform',
            fullName: 'Crazy:B Training Uniform (Rinne)',
            crafted: true,
            id: 'ae017f83-28a0-4af1-ab7e-523885272259',
            index: 25,
          },
          {
            group: 'general',
            Ac: 0,
            Pa: 20,
            Un: 0,
            Sm: 25,
            Te: 0,
            Ch: 35,
            idol: 'Rinne',
            name: 'ES Idol Uniform',
            fullName: 'ES Idol Uniform (Rinne)',
            crafted: false,
            id: '5972fc7c-e265-4251-a8d3-0696d070e564',
            index: 74,
          },
        ],
      },
      HiMERU: {
        general: [
          {
            group: 'general',
            Ac: 0,
            Pa: 0,
            Un: 0,
            Sm: 0,
            Te: 0,
            Ch: 0,
            idol: 'HiMERU',
            name: 'Crazy:B Training Uniform',
            fullName: 'Crazy:B Training Uniform (HiMERU)',
            crafted: true,
            id: 'ac47f8a5-dca9-4d6c-b8db-37689457aa78',
            index: 26,
          },
          {
            group: 'general',
            Ac: 0,
            Pa: 0,
            Un: 20,
            Sm: 0,
            Te: 35,
            Ch: 25,
            idol: 'HiMERU',
            name: 'ES Idol Uniform',
            fullName: 'ES Idol Uniform (HiMERU)',
            crafted: false,
            id: '0f375ddf-1ddc-4fa7-a7e8-d80f0aaccec8',
            index: 75,
          },
        ],
      },
      Kohaku: {
        general: [
          {
            group: 'general',
            Ac: 0,
            Pa: 0,
            Un: 0,
            Sm: 0,
            Te: 0,
            Ch: 0,
            idol: 'Kohaku',
            name: 'Crazy:B Training Uniform',
            fullName: 'Crazy:B Training Uniform (Kohaku)',
            crafted: true,
            id: 'd3e82347-3196-44f1-a4f0-b009b9f61365',
            index: 27,
          },
          {
            group: 'general',
            Ac: 0,
            Pa: 0,
            Un: 0,
            Sm: 35,
            Te: 25,
            Ch: 20,
            idol: 'Kohaku',
            name: 'ES Idol Uniform',
            fullName: 'ES Idol Uniform (Kohaku)',
            crafted: false,
            id: '0e8fb4e4-15c2-4b06-8419-b18a70824048',
            index: 76,
          },
        ],
      },
      Niki: {
        general: [
          {
            group: 'general',
            Ac: 0,
            Pa: 0,
            Un: 0,
            Sm: 0,
            Te: 0,
            Ch: 0,
            idol: 'Niki',
            name: 'Crazy:B Training Uniform',
            fullName: 'Crazy:B Training Uniform (Niki)',
            crafted: true,
            id: '664c4ad1-e071-48e2-a20f-3c52e3c3f9fa',
            index: 28,
          },
          {
            group: 'general',
            Ac: 40,
            Pa: 20,
            Un: 0,
            Sm: 0,
            Te: 0,
            Ch: 20,
            idol: 'Niki',
            name: 'ES Idol Uniform',
            fullName: 'ES Idol Uniform (Niki)',
            crafted: false,
            id: '7bafa18c-e2e1-4c62-be69-6c9aace1ad32',
            index: 77,
          },
        ],
      },
      Rei: {
        general: [
          {
            group: 'general',
            Ac: 0,
            Pa: 0,
            Un: 0,
            Sm: 0,
            Te: 0,
            Ch: 0,
            idol: 'Rei',
            name: 'UNDEAD Training Uniform',
            fullName: 'UNDEAD Training Uniform (Rei)',
            crafted: true,
            id: 'efa3b583-222d-4ee3-9e2d-038d9fda671d',
            index: 29,
          },
          {
            group: 'general',
            Ac: 20,
            Pa: 0,
            Un: 35,
            Sm: 0,
            Te: 0,
            Ch: 25,
            idol: 'Rei',
            name: 'ES Idol Uniform',
            fullName: 'ES Idol Uniform (Rei)',
            crafted: false,
            id: 'bcf50e2c-3890-4dac-bdd9-f8a17dae5d83',
            index: 78,
          },
        ],
      },
      Kaoru: {
        general: [
          {
            group: 'general',
            Ac: 0,
            Pa: 0,
            Un: 0,
            Sm: 0,
            Te: 0,
            Ch: 0,
            idol: 'Kaoru',
            name: 'UNDEAD Training Uniform',
            fullName: 'UNDEAD Training Uniform (Kaoru)',
            crafted: true,
            id: '7329dfae-d396-421f-9582-c2095b4969d1',
            index: 30,
          },
          {
            group: 'general',
            Ac: 0,
            Pa: 20,
            Un: 35,
            Sm: 25,
            Te: 0,
            Ch: 0,
            idol: 'Kaoru',
            name: 'ES Idol Uniform',
            fullName: 'ES Idol Uniform (Kaoru)',
            crafted: false,
            id: '4bb7ed92-abfb-486b-aa2f-95075b4c3568',
            index: 79,
          },
        ],
      },
      Koga: {
        general: [
          {
            group: 'general',
            Ac: 0,
            Pa: 0,
            Un: 0,
            Sm: 0,
            Te: 0,
            Ch: 0,
            idol: 'Koga',
            name: 'UNDEAD Training Uniform',
            fullName: 'UNDEAD Training Uniform (Koga)',
            crafted: true,
            id: 'b118e34f-0a9d-416f-97e4-5ebede598c4d',
            index: 31,
          },
          {
            group: 'general',
            Ac: 0,
            Pa: 25,
            Un: 20,
            Sm: 0,
            Te: 35,
            Ch: 0,
            idol: 'Koga',
            name: 'ES Idol Uniform',
            fullName: 'ES Idol Uniform (Koga)',
            crafted: false,
            id: '2964ee7f-975a-4f97-a0bd-27b8e09bbf39',
            index: 80,
          },
        ],
      },
      Adonis: {
        general: [
          {
            group: 'general',
            Ac: 0,
            Pa: 0,
            Un: 0,
            Sm: 0,
            Te: 0,
            Ch: 0,
            idol: 'Adonis',
            name: 'UNDEAD Training Uniform',
            fullName: 'UNDEAD Training Uniform (Adonis)',
            crafted: true,
            id: 'b9e2ad9f-b9eb-4534-8ba8-f63978a157a3',
            index: 32,
          },
          {
            group: 'general',
            Ac: 35,
            Pa: 0,
            Un: 25,
            Sm: 20,
            Te: 0,
            Ch: 0,
            idol: 'Adonis',
            name: 'ES Idol Uniform',
            fullName: 'ES Idol Uniform (Adonis)',
            crafted: false,
            id: '5b5c7f18-2b54-4f83-ab6d-e0702b2dffe5',
            index: 81,
          },
        ],
      },
      Tomoya: {
        general: [
          {
            group: 'general',
            Ac: 0,
            Pa: 0,
            Un: 0,
            Sm: 0,
            Te: 0,
            Ch: 0,
            idol: 'Tomoya',
            name: 'Ra*bits Training Uniform',
            fullName: 'Ra*bits Training Uniform (Tomoya)',
            crafted: true,
            id: '7332f071-95b8-4c50-ac8a-efced16bae4d',
            index: 33,
          },
          {
            group: 'general',
            Ac: 0,
            Pa: 40,
            Un: 0,
            Sm: 20,
            Te: 0,
            Ch: 20,
            idol: 'Tomoya',
            name: 'ES Idol Uniform',
            fullName: 'ES Idol Uniform (Tomoya)',
            crafted: false,
            id: '5640df74-0b05-462a-9d8f-5bfe0582b68c',
            index: 82,
          },
        ],
      },
      Nazuna: {
        general: [
          {
            group: 'general',
            Ac: 0,
            Pa: 0,
            Un: 0,
            Sm: 0,
            Te: 0,
            Ch: 0,
            idol: 'Nazuna',
            name: 'Ra*bits Training Uniform',
            fullName: 'Ra*bits Training Uniform (Nazuna)',
            crafted: true,
            id: 'a1373ce0-3799-4593-9d2f-26bd5f78ade6',
            index: 34,
          },
          {
            group: 'general',
            Ac: 0,
            Pa: 25,
            Un: 20,
            Sm: 0,
            Te: 0,
            Ch: 35,
            idol: 'Nazuna',
            name: 'ES Idol Uniform',
            fullName: 'ES Idol Uniform (Nazuna)',
            crafted: false,
            id: '4b9f8f95-ae5a-41a7-aa5c-88da1edfdb63',
            index: 83,
          },
        ],
      },
      Mitsuru: {
        general: [
          {
            group: 'general',
            Ac: 0,
            Pa: 0,
            Un: 0,
            Sm: 0,
            Te: 0,
            Ch: 0,
            idol: 'Mitsuru',
            name: 'Ra*bits Training Uniform',
            fullName: 'Ra*bits Training Uniform (Mitsuru)',
            crafted: true,
            id: '9221f2c8-e02f-452c-9c91-b9636048b7a0',
            index: 35,
          },
          {
            group: 'general',
            Ac: 20,
            Pa: 0,
            Un: 0,
            Sm: 25,
            Te: 0,
            Ch: 35,
            idol: 'Mitsuru',
            name: 'ES Idol Uniform',
            fullName: 'ES Idol Uniform (Mitsuru)',
            crafted: false,
            id: '877fcdbf-f441-4aa6-8254-a91384dc410c',
            index: 84,
          },
        ],
      },
      Hajime: {
        general: [
          {
            group: 'general',
            Ac: 0,
            Pa: 0,
            Un: 0,
            Sm: 0,
            Te: 0,
            Ch: 0,
            idol: 'Hajime',
            name: 'Ra*bits Training Uniform',
            fullName: 'Ra*bits Training Uniform (Hajime)',
            crafted: true,
            id: 'b0f8be74-bd8d-4596-b59b-70a3b9172052',
            index: 36,
          },
          {
            group: 'general',
            Ac: 0,
            Pa: 20,
            Un: 0,
            Sm: 20,
            Te: 40,
            Ch: 0,
            idol: 'Hajime',
            name: 'ES Idol Uniform',
            fullName: 'ES Idol Uniform (Hajime)',
            crafted: false,
            id: 'dcad9acf-e671-4ee7-b6f3-a57d4199bc26',
            index: 85,
          },
        ],
      },
      Keito: {
        general: [
          {
            group: 'general',
            Ac: 0,
            Pa: 0,
            Un: 0,
            Sm: 0,
            Te: 0,
            Ch: 0,
            idol: 'Keito',
            name: 'AKATSUKI Training Uniform',
            fullName: 'AKATSUKI Training Uniform (Keito)',
            crafted: true,
            id: '3d8f92b6-8768-4fde-81de-9cf555e58efb',
            index: 37,
          },
          {
            group: 'general',
            Ac: 20,
            Pa: 40,
            Un: 0,
            Sm: 0,
            Te: 20,
            Ch: 0,
            idol: 'Keito',
            name: 'ES Idol Uniform',
            fullName: 'ES Idol Uniform (Keito)',
            crafted: false,
            id: 'd8812a35-0fe9-408b-b796-c0a77befc3ba',
            index: 86,
          },
        ],
      },
      Kuro: {
        general: [
          {
            group: 'general',
            Ac: 0,
            Pa: 0,
            Un: 0,
            Sm: 0,
            Te: 0,
            Ch: 0,
            idol: 'Kuro',
            name: 'AKATSUKI Training Uniform',
            fullName: 'AKATSUKI Training Uniform (Kuro)',
            crafted: true,
            id: 'f8a6adf8-c904-4a0b-8129-ed60ec01ace3',
            index: 38,
          },
          {
            group: 'general',
            Ac: 35,
            Pa: 0,
            Un: 0,
            Sm: 20,
            Te: 25,
            Ch: 0,
            idol: 'Kuro',
            name: 'ES Idol Uniform',
            fullName: 'ES Idol Uniform (Kuro)',
            crafted: false,
            id: 'd953ecd1-5fc4-443a-81b7-e127be2ccdc7',
            index: 87,
          },
        ],
      },
      Souma: {
        general: [
          {
            group: 'general',
            Ac: 0,
            Pa: 0,
            Un: 0,
            Sm: 0,
            Te: 0,
            Ch: 0,
            idol: 'Souma',
            name: 'AKATSUKI Training Uniform',
            fullName: 'AKATSUKI Training Uniform (Souma)',
            crafted: true,
            id: '1ebbb1f2-4ccf-425f-b8e4-ab3c8c43b402',
            index: 39,
          },
          {
            group: 'general',
            Ac: 40,
            Pa: 20,
            Un: 0,
            Sm: 20,
            Te: 0,
            Ch: 0,
            idol: 'Souma',
            name: 'ES Idol Uniform',
            fullName: 'ES Idol Uniform (Souma)',
            crafted: false,
            id: '33ba4747-9ff2-4bde-8a65-36266568bbef',
            index: 88,
          },
        ],
      },
      Tsukasa: {
        general: [
          {
            group: 'general',
            Ac: 0,
            Pa: 0,
            Un: 0,
            Sm: 0,
            Te: 0,
            Ch: 0,
            idol: 'Tsukasa',
            name: 'Knights Training Uniform',
            fullName: 'Knights Training Uniform (Tsukasa)',
            crafted: true,
            id: '8ec1c08c-c852-4392-9f72-cc008d54f2c9',
            index: 40,
          },
          {
            group: 'general',
            Ac: 25,
            Pa: 0,
            Un: 35,
            Sm: 0,
            Te: 0,
            Ch: 20,
            idol: 'Tsukasa',
            name: 'ES Idol Uniform',
            fullName: 'ES Idol Uniform (Tsukasa)',
            crafted: false,
            id: '8d09e90f-8170-4225-8c39-bdc964eb6b85',
            index: 89,
          },
        ],
      },
      Leo: {
        general: [
          {
            group: 'general',
            Ac: 0,
            Pa: 0,
            Un: 0,
            Sm: 0,
            Te: 0,
            Ch: 0,
            idol: 'Leo',
            name: 'Knights Training Uniform',
            fullName: 'Knights Training Uniform (Leo)',
            crafted: true,
            id: 'afb76d25-f56c-4c16-bab6-f03ed9968ac8',
            index: 41,
          },
          {
            group: 'general',
            Ac: 0,
            Pa: 0,
            Un: 25,
            Sm: 0,
            Te: 35,
            Ch: 20,
            idol: 'Leo',
            name: 'ES Idol Uniform',
            fullName: 'ES Idol Uniform (Leo)',
            crafted: false,
            id: '9c5bd06e-bafe-4679-98a4-0aa5648579d1',
            index: 90,
          },
        ],
      },
      Izumi: {
        general: [
          {
            group: 'general',
            Ac: 0,
            Pa: 0,
            Un: 0,
            Sm: 0,
            Te: 0,
            Ch: 0,
            idol: 'Izumi',
            name: 'Knights Training Uniform',
            fullName: 'Knights Training Uniform (Izumi)',
            crafted: true,
            id: '4276526a-dfbf-4ac5-85ad-924d37b71068',
            index: 42,
          },
          {
            group: 'general',
            Ac: 35,
            Pa: 0,
            Un: 20,
            Sm: 25,
            Te: 0,
            Ch: 0,
            idol: 'Izumi',
            name: 'ES Idol Uniform',
            fullName: 'ES Idol Uniform (Izumi)',
            crafted: false,
            id: 'bdf82465-ecd2-43bc-a9a0-2d29bde6eb9b',
            index: 91,
          },
        ],
      },
      Ritsu: {
        general: [
          {
            group: 'general',
            Ac: 0,
            Pa: 0,
            Un: 0,
            Sm: 0,
            Te: 0,
            Ch: 0,
            idol: 'Ritsu',
            name: 'Knights Training Uniform',
            fullName: 'Knights Training Uniform (Ritsu)',
            crafted: true,
            id: '78557d21-918e-4a04-aa04-3025f942b476',
            index: 43,
          },
          {
            group: 'general',
            Ac: 25,
            Pa: 0,
            Un: 0,
            Sm: 0,
            Te: 20,
            Ch: 35,
            idol: 'Ritsu',
            name: 'ES Idol Uniform',
            fullName: 'ES Idol Uniform (Ritsu)',
            crafted: false,
            id: 'e20e894e-e03d-413e-a445-e1ad573fba93',
            index: 92,
          },
        ],
      },
      Arashi: {
        general: [
          {
            group: 'general',
            Ac: 0,
            Pa: 0,
            Un: 0,
            Sm: 0,
            Te: 0,
            Ch: 0,
            idol: 'Arashi',
            name: 'Knights Training Uniform',
            fullName: 'Knights Training Uniform (Arashi)',
            crafted: true,
            id: 'c16c58fd-efcf-4e8d-9d5c-e7b73dd7b794',
            index: 44,
          },
          {
            group: 'general',
            Ac: 0,
            Pa: 35,
            Un: 0,
            Sm: 0,
            Te: 20,
            Ch: 25,
            idol: 'Arashi',
            name: 'ES Idol Uniform',
            fullName: 'ES Idol Uniform (Arashi)',
            crafted: false,
            id: 'dc269ece-211c-4797-b309-b65b82e1a891',
            index: 93,
          },
        ],
      },
      Natsume: {
        general: [
          {
            group: 'general',
            Ac: 0,
            Pa: 0,
            Un: 0,
            Sm: 0,
            Te: 0,
            Ch: 0,
            idol: 'Natsume',
            name: 'Switch Training Uniform',
            fullName: 'Switch Training Uniform (Natsume)',
            crafted: true,
            id: '8a1b4910-90e1-48f6-ab58-cdd2b42e6da0',
            index: 45,
          },
          {
            group: 'general',
            Ac: 0,
            Pa: 0,
            Un: 20,
            Sm: 25,
            Te: 35,
            Ch: 0,
            idol: 'Natsume',
            name: 'ES Idol Uniform',
            fullName: 'ES Idol Uniform (Natsume)',
            crafted: false,
            id: '3da926dd-9bd3-416d-ac7e-ce1a787afbab',
            index: 94,
          },
        ],
      },
      Tsumugi: {
        general: [
          {
            group: 'general',
            Ac: 0,
            Pa: 0,
            Un: 0,
            Sm: 0,
            Te: 0,
            Ch: 0,
            idol: 'Tsumugi',
            name: 'Switch Training Uniform',
            fullName: 'Switch Training Uniform (Tsumugi)',
            crafted: true,
            id: 'b7c2d57d-f17e-4cc6-9708-c1c3bf35f60b',
            index: 46,
          },
          {
            group: 'general',
            Ac: 25,
            Pa: 0,
            Un: 0,
            Sm: 35,
            Te: 20,
            Ch: 0,
            idol: 'Tsumugi',
            name: 'ES Idol Uniform',
            fullName: 'ES Idol Uniform (Tsumugi)',
            crafted: false,
            id: '32c1e1c0-5096-4cf1-b410-dea87454c1c5',
            index: 95,
          },
        ],
      },
      Sora: {
        general: [
          {
            group: 'general',
            Ac: 0,
            Pa: 0,
            Un: 0,
            Sm: 0,
            Te: 0,
            Ch: 0,
            idol: 'Sora',
            name: 'Switch Training Uniform',
            fullName: 'Switch Training Uniform (Sora)',
            crafted: true,
            id: 'ecee6024-742a-4e0e-b10a-18391e103392',
            index: 47,
          },
          {
            group: 'general',
            Ac: 20,
            Pa: 25,
            Un: 35,
            Sm: 0,
            Te: 0,
            Ch: 0,
            idol: 'Sora',
            name: 'ES Idol Uniform',
            fullName: 'ES Idol Uniform (Sora)',
            crafted: false,
            id: '9effbddd-4af7-4758-9ea9-3eb1d2013f9b',
            index: 96,
          },
        ],
      },
      Madara: {
        general: [
          {
            group: 'general',
            Ac: 0,
            Pa: 0,
            Un: 0,
            Sm: 0,
            Te: 0,
            Ch: 0,
            idol: 'Madara',
            name: 'MaM Training Uniform',
            fullName: 'MaM Training Uniform (Madara)',
            crafted: true,
            id: '526ae3ca-074b-4089-b906-bd885417226a',
            index: 48,
          },
          {
            group: 'general',
            Ac: 20,
            Pa: 0,
            Un: 0,
            Sm: 35,
            Te: 25,
            Ch: 0,
            idol: 'Madara',
            name: 'ES Idol Uniform',
            fullName: 'ES Idol Uniform (Madara)',
            crafted: false,
            id: '9c5a029a-d72d-4932-b9a5-a9e6f0667c9b',
            index: 97,
          },
        ],
      },
    },
  },
}
